/**
 * ELF parser unit tests over the deterministic fixtures generated by
 * tools/gen-elf-fixtures.mjs (hello / infected / weird / tiny).
 */
import { test } from "node:test";
import assert from "node:assert/strict";

import { parseElf, hexdump } from "../src/elf/parse.mjs";
import { FIXTURES } from "../src/elf/fixtures.gen.mjs";

test("hello.elf parses as a clean x86-64 ET_EXEC", () => {
  const p = parseElf(FIXTURES.hello);
  assert.equal(p.bits, 64);
  assert.equal(p.ehdr.typeName, "ET_EXEC");
  assert.equal(p.ehdr.machineName, "EM_X86_64");
  assert.equal(p.ehdr.entry, 0x400100n);
  // two loads + one note, all recognized types
  const types = p.phdrs.map((ph) => ph.typeName);
  assert.deepEqual(types, ["PT_LOAD", "PT_LOAD", "PT_NOTE"]);
  assert.ok(p.phdrs[0].flagStr.includes("x"));
  // congruence: vaddr ≡ offset (mod align) holds everywhere -> no anomaly
  assert.deepEqual(p.anomalies, []);
});

test("hello.elf exposes sections and symbols", () => {
  const p = parseElf(FIXTURES.hello);
  const names = p.shdrs.map((s) => s.name);
  for (const want of [".text", ".data", ".symtab", ".strtab"]) {
    assert.ok(names.includes(want), `missing section ${want}`);
  }
  const syms = Object.fromEntries(p.symbols.map((s) => [s.name, s]));
  assert.equal(syms["_start"].value, 0x400100n);
  assert.equal(syms["_start"].typeName, "FUNC");
  assert.equal(syms["kf_greet"].value, 0x400130n);
  assert.equal(syms["secret_msg"].typeName, "OBJECT");
  assert.equal(syms["secret_msg"].size, 11n);
  // strings view finds the data segment payload
  const texts = p.strings(6).map((s) => s.text);
  assert.ok(texts.includes("hello tmpout"));
});

test("infected.elf hides a PT_NOTE parasite at EOF with movabs OEP stub", () => {
  const p = parseElf(FIXTURES.infected);
  assert.equal(p.size, FIXTURES.hello.length + 23); // marker(11)+stub(12)
  // phdr[2] was repurposed: PT_LOAD at a far VA covering old EOF
  const par = p.phdrs[2];
  assert.equal(par.typeName, "PT_LOAD");
  assert.equal(par.offset, BigInt(FIXTURES.hello.length));
  assert.equal(par.vaddr, 0xc000000n + BigInt(FIXTURES.hello.length));
  assert.equal(p.ehdr.entry, par.vaddr);
  // structurally quiet: parser anomalies stay empty (the point of the method)
  assert.deepEqual(p.anomalies, []);
  // OEP bytes visible at parasite+11: 48 b8 <0x400100 LE> ff e0
  const off = Number(par.offset) + 11;
  assert.equal(p.bytes[off], 0x48);
  assert.equal(p.bytes[off + 1], 0xb8);
  assert.equal(p.bytes[off + 10], 0xff);
  assert.equal(p.bytes[off + 11], 0xe0);
});

test("weird.elf survives extended numbering and reports its traps", () => {
  const p = parseElf(FIXTURES.weird);
  // true section count recovered from shdr[0].sh_size
  assert.equal(p.shdrs.length, 6);
  // shstrndx resolved from shdr[0].sh_link -> names resolve
  assert.ok(p.shdrs.some((s) => s.name === ".past-eof"));
  const notes = p.anomalies.join("\n");
  assert.match(notes, /extended numbering/);
  assert.match(notes, /SHN_XINDEX/);
  assert.match(notes, /past EOF/);
  assert.match(notes, /sh_entsize 0/);
});

test("tiny.elf mimics kernel zero-padding on a truncated header", () => {
  assert.equal(FIXTURES.tiny.length, 57);
  const p = parseElf(FIXTURES.tiny);
  assert.equal(p.ehdr.phnum, 1); // high byte elided, still reads as 1
  assert.equal(p.ehdr.phoff, 0n);
  // aliased Phdr's p_type IS the ELF magic
  assert.equal(p.phdrs[0].type, 0x464c457f);
  const notes = p.anomalies.join("\n");
  assert.match(notes, /aliases the Ehdr/);
  assert.match(notes, /unrecognized p_type unknown\(0x464c457f\)/);
});

test("hexdump renders stable output", () => {
  const lines = hexdump(FIXTURES.hello, 0, 16).split("\n");
  assert.equal(lines.length, 1);
  assert.match(lines[0], /^00000000: 7f 45 4c 46/);
});
